export const CONTACT_ADD_REQUEST = "CONTACT_ADD_REQUEST"
export const CONTACT_ADD_SUCCESS = "CONTACT_ADD_SUCCESS"
export const CONTACT_ADD_FAIL = "CONTACT_ADD_FAIL"

export const GET_ALL_CONTACT_REQUEST = "GET_ALL_CONTACT_REQUEST"
export const GET_ALL_CONTACT_SUCCESS = "GET_ALL_CONTACT_SUCCESS"
export const GET_ALL_CONTACT_FAIL = "GET_ALL_CONTACT_FAIL"