export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST"
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS"
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL"

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST"
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS"
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL"

export const GET_ALL_DATA_REQUEST = "GET_ALL_DATA_REQUEST"
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_REQUEST_SUCCESS"
export const GET_ALL_DATA_FAIL = "GET_ALL_DATA_REQUEST_FAIL"

export const EDIT_ACCOUNT_REQUEST = "EDIT_ACCOUNT_REQUEST"
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS"
export const EDIT_ACCOUNT_FAIL = "EDIT_ACCOUNT_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"